# Generated by Django 5.0.4 on 2024-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name="Person's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="Person's last name")),
                ('dob', models.DateField(verbose_name="Person's Date Of Birth")),
                ('contact_number', models.CharField(max_length=15, verbose_name="Person's Contact Number")),
                ('mail_address', models.EmailField(max_length=50, verbose_name="Peron's Mail Address")),
                ('address', models.CharField(max_length=500, verbose_name="Person's Address")),
            ],
        ),
    ]
