# Generated by Django 5.0.4 on 2024-04-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelAutosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_number', models.CharField(max_length=30, unique=True, verbose_name='Insurance Number')),
                ('start_date', models.DateField(verbose_name='Insurance start  date')),
                ('end_date', models.DateField(verbose_name='Insurance end  date')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30, verbose_name='Service Name')),
                ('service_charges', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30, unique=True, verbose_name='2/3/4/.. wheeler')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='users_slug',
            field=models.SlugField(default='users_slug'),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True, verbose_name="Person's Contact Number"),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='.', max_length=30, verbose_name="Person's last name"),
        ),
        migrations.AlterField(
            model_name='users',
            name='mail_address',
            field=models.EmailField(max_length=50, unique=True, verbose_name="Peron's Mail Address"),
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=15, unique=True, verbose_name='Vehicle Number')),
                ('brand_name', models.CharField(max_length=30, verbose_name='Brand name of the vehicle')),
                ('model_name', models.CharField(max_length=30, verbose_name='Model name of the Vehicle')),
                ('manufacture_year', models.PositiveIntegerField()),
                ('insurance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.insurance')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.users')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('admit_date', models.DateTimeField(verbose_name='Date when vehicle is taken for servicing')),
                ('deliver_date', models.DateTimeField(verbose_name='Date when vehicle is delivered after servicing')),
                ('total_charges', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount_applied', models.PositiveIntegerField()),
                ('paid_charges', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleServicings',
            fields=[
                ('vehicle_servicing_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.bills')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.services')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvelAutosApp.vehicletype'),
        ),
    ]
